[package]
name = "fmp"
version = "1.1.0"
edition = "2025"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
cmd_lib = "1.9.5"
rustc-serialize = "0.3"
rand = "0.8.5"
simple-home-dir = "0.4.5"
